apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd-helm
  namespace: user1-argocd
spec:
  destination:
    name: ''
    namespace: poc-clh-3
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://victorfernandezarias.github.io/poc-gitops-github/'
    targetRevision: 1.0.0
    chart: bgd
    helm:
      parameters:
        - name: color
          value: blue
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
