apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd-kustomize
  namespace: user1-argocd
spec:
  destination:
    namespace: poc-clh-3
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomize/components/overlays
    repoURL: https://github.com/VictorFernandezArias/poc-gitops-github.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
